In [1]:
lst = [1,2,3]

In [2]:
lst

[1, 2, 3]

In [3]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
lst2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
import numpy as np

In [7]:
np.array(lst)

array([1, 2, 3])

In [8]:
np.array(lst2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array(lst).max()

3

In [10]:
np.array(lst2).max()

9

In [11]:
np.array(lst).mean()

2.0

In [12]:
np.arange(0,1)

array([0])

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
# array indexing... 1D array..

arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr[8]

8

In [20]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[4:2]

array([], dtype=int64)

In [22]:
arr[:-0]

array([], dtype=int64)

In [23]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[:4]

array([0, 1, 2, 3])

In [30]:
arr[0:4] = 444

In [31]:
arr

array([444, 444, 444, 444,   4,   5,   6,   7,   8,   9,  10])

In [32]:
arr[:] = 999

In [33]:
arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [34]:
arr_copy = arr.copy()

In [35]:
arr_copy

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [36]:
arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [37]:
arr

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [38]:
arr[:] = [0,1,2,3,4,5,6,7,8,9,10]

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_copy

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [42]:
# 2D array indexing and slicing...

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[0]

array([1, 2, 3])

In [49]:
arr2d[1][0]

4

In [52]:
arr2d[1,0]

4

In [56]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [60]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr<3]

array([0, 1, 2])

In [62]:
arr[arr== 5]

array([5])

In [69]:
arr2 = np.arange(50).reshape(5,10)

In [70]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
arr2[:4,6:]

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39]])

In [74]:
arr = np.arange(0,10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
arr*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [80]:
arr/arr

/Users/sbandi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [81]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [82]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [83]:
arr.max()

9

In [84]:
max(arr)

9

In [85]:
arr.min()

0

In [86]:
arr.mean()

4.5

In [90]:
#arr.sqrt()

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])